const BURNING_ENERGY_RATE = 420
const BURNING_BANDWIDTH_RATE = 1000
const ESTIMATE_TRANSFER_TRX_BANDWIDTH_COST = 300

export {
    BURNING_ENERGY_RATE,
    BURNING_BANDWIDTH_RATE,
    ESTIMATE_TRANSFER_TRX_BANDWIDTH_COST
}